# -*- coding: utf-8 -*-
"""Copy of EAS ML_039_095.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7bHM4bGDC4lk0Mf-KNPzSsJKkIu0hyS
"""


import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

test_df = pd.read_csv('/content/test.csv')

df = pd.read_csv('/content/test.csv')

df.head()

df.info()

df.isnull().sum()

if "Unnamed: 0" in df.columns:
    df.drop("Unnamed: 0", axis=1, inplace=True)

if "id" in df.columns:
    df.drop("id", axis=1, inplace=True)

df.fillna(df.median(numeric_only=True), inplace=True)

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

df.describe()
df['satisfaction'].value_counts()

import matplotlib.pyplot as plt

# Hitung jumlah satisfaction
satisfaction_counts = df['satisfaction'].value_counts()

# Label
labels = ['Dissatisfied (0)', 'Satisfied (1)']

# Warna pink
colors = ["#FFB6C1","#DB2777"]

# Plot donut chart
plt.figure(figsize=(7,7))

plt.pie(
    satisfaction_counts,
    labels=labels,
    colors=colors,
    autopct='%1.1f%%',
    startangle=90,
    pctdistance=0.80,
    wedgeprops=dict(width=0.4)  # bikin donut
)

plt.title(
    "Distribution of Satisfaction",
    fontsize=16,
    fontweight='bold'
)

plt.show()

y = df['satisfaction']
X = df.drop('satisfaction', axis=1)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Jumlah data training:", X_train.shape[0])
print("Jumlah data testing:", X_test.shape[0])

print("Shape X_train:", X_train.shape)
print("Shape X_test:", X_test.shape)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

import pickle
pickle.dump(scaler, open('scaler.pkl','wb'))

lr = LogisticRegression(max_iter=5000)

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

xgb = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    random_state=42
)

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)

def evaluate_model(model_name, y_true, y_pred):

    accuracy = accuracy_score(y_true, y_pred)

    precision = precision_score(
        y_true,
        y_pred,
        average='weighted'
    )

    recall = recall_score(
        y_true,
        y_pred,
        average='weighted'
    )

    f1 = f1_score(
        y_true,
        y_pred,
        average='weighted'
    )

    return [
        model_name,
        accuracy,
        precision,
        recall,
        f1
    ]

results = []

results.append(
    evaluate_model(
        "Logistic Regression",
        y_test,
        y_pred_lr
    )
)

results.append(
    evaluate_model(
        "Random Forest",
        y_test,
        y_pred_rf
    )
)

results.append(
    evaluate_model(
        "XGBoost",
        y_test,
        y_pred_xgb
    )
)

result_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
)

result_df

# save
import joblib
joblib.dump(result_df, "metrics.pkl")

result_df.set_index("Model").plot(
    kind="bar",
    figsize=(10,6)
)

plt.title("Perbandingan Model")
plt.ylabel("Score")
plt.show()

from sklearn.metrics import confusion_matrix

from matplotlib.colors import LinearSegmentedColormap

pink_cmap = LinearSegmentedColormap.from_list(
    "custom_pink",
    ["#FFF0F5", "#FFB6C1", "#FF69B4", "#DB2777"]
)

cm = confusion_matrix(y_test, y_pred_xgb)

plt.figure(figsize=(6,4))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap=pink_cmap
)

plt.title("Confusion Matrix XGBoost")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

print(classification_report(
    y_test,
    y_pred_xgb
))

# Commented out IPython magic to ensure Python compatibility.
# %whos

importance = xgb.feature_importances_

feat_imp = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importance
}).sort_values(by='Importance', ascending=False)

import joblib

joblib.dump(
    xgb,
    "model_xgboost.pkl"
)

from google.colab import files
files.download("model_xgboost.pkl")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.set_page_config(
#     page_title="Airline Satisfaction Dashboard",
#     page_icon="✈️",
#     layout="wide",
#     initial_sidebar_state="expanded"
# )
# # =========================
# # GLOBAL CSS
# # =========================
# st.markdown("""
# <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&family=Poppins:wght@500;600;700;800&display=swap" rel="stylesheet">
# 
# <style>
# 
# html, body, [class*="css"] {
#     font-family: 'Poppins', poppins;
# }
# 
# .stApp {
#     font-family: 'Poppins';
#     background: linear-gradient(
#         180deg,
#         #F8FAFC 0%,
#         #EFF6FF 100%
#     );
# }
# /* SIDEBAR */
# [data-testid="stSidebar"] {
#     font-family: 'Poppins';
#     background:
#     linear-gradient(
#         180deg,
#         #081F5C 0%,
#         #0F52BA 45%,
#         #2563EB 100%
#     );
#     padding-top: 20px;
# }
# 
# [data-testid="stSidebar"] * {
#     color: white;
# }
# .sidebar-logo {
#     font-family: 'Poppins';
#     background: rgba(255,255,255,0.10);
#     border-radius: 18px;
#     padding: 20px;
#     text-align: center;
#     margin-bottom: 25px;
# }
# 
# .main-title {
#     font-family: 'Poppins', poppins;
#     font-size: 48px;
#     font-weight: 800;
#     color: #0F172A;
# }
# 
# .subtitle {
#     font-family: 'Poppins';
#     font-size: 18px;
#     color: #475569;
#     margin-bottom: 35px;
# }
# 
# .primary-card {
# font-family: 'Poppins';
#     background: linear-gradient(
#         135deg,
#         #081F5C 0%,
#         #1E3A8A 100%
#     );
#     border-radius: 22px;
#     padding: 28px;
#     color: white;
# }
# 
# .secondary-card {
# font-family: 'Poppins';
#     background: linear-gradient(
#         135deg,
#         #DBEAFE 0%,
#         #EFF6FF 100%
#     );
#     border-left: 5px solid #2563EB;
#     border-radius: 18px;
#     padding: 22px;
# }
# 
# .section-title {
#     font-family: 'Poppins';
#     font-size: 28px;
#     font-weight: 800;
#     color: #1E3A8A;
# }
# </style>
# """, unsafe_allow_html=True)
# 
# # ==========================
# # SIDEBAR
# # ==========================
# st.sidebar.markdown("""
# <div class="sidebar-logo">
#     <h2>✈ AirInsight</h2>
#     <p>Passenger Analytics System</p>
# </div>
# """, unsafe_allow_html=True)
# 
# st.sidebar.markdown("---")
# 
# st.sidebar.subheader("Navigation")
# 
# st.sidebar.info(
#     "Explore analytical insights, compare machine learning models, and simulate passenger satisfaction predictions."
# )
# 
# st.markdown("""
# <div class="main-title">✈ Airline Passenger Satisfaction Dashboard</div>
# <div class="subtitle">
# Comprehensive analytics for customer behavior, model comparison, and predictive insights.
# </div>
# """, unsafe_allow_html=True)
# 
# st.markdown("""
# <div class="primary-card">
# <h3>Dashboard Overview</h3>
# <p>
# Analyze airline passenger satisfaction using interactive visual analytics,
# machine learning model evaluation, and prediction simulation.
# </p>
# </div>
# """, unsafe_allow_html=True)
# 
# st.markdown("<br>", unsafe_allow_html=True)
# 
# st.markdown('<div class="section-title">Dashboard Modules</div>', unsafe_allow_html=True)
# 
# col1, col2, col3 = st.columns(3)
# 
# modules = [
#     ("📊 Dashboard Analysis", "Explore passenger demographics and service quality."),
#     ("📉 Model Evaluation", "Compare model performance and feature importance."),
#     ("🔮 Prediction", "Predict satisfaction in real-time.")
# ]
# 
# for col, (title, desc) in zip([col1, col2, col3], modules):
#     with col:
#         st.markdown(f"""
#         <div class="secondary-card">
#         <h4>{title}</h4>
#         <p>{desc}</p>
#         </div>
#         """, unsafe_allow_html=True)


# Commented out IPython magic to ensure Python compatibility.
# %%writefile pages/1_Dashboard_Analysis.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# # ==========================
# # PAGE CONFIG
# # ==========================
# st.set_page_config(
#     page_title="Dashboard Analysis",
#     page_icon="📊",
#     layout="wide"
# )
# 
# # ==========================
# # LOAD DATA
# # ==========================
# df = pd.read_csv("/content/test.csv")
# 
# # ==========================
# # COLOR PALETTE
# # ==========================
# chart_colors = [
#     "#BFDBFE",  # soft blue
#     "#60A5FA",  # medium blue
#     "#DBEAFE"   # icy blue
# ]
# 
# # ==========================
# # GLOBAL CSS
# # ==========================
# st.markdown("""
# <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
# 
# <style>
# 
# html, body, [class*="css"] {
#     font-family: 'Poppins', poppins;
# }
# 
# /* SIDEBAR */
# [data-testid="stSidebar"] {
#     font-family: 'Poppins';
#     background:
#     linear-gradient(
#         180deg,
#         #081F5C 0%,
#         #0F52BA 45%,
#         #2563EB 100%
#     );
#     padding-top: 20px;
# }
# 
# [data-testid="stSidebar"] * {
#     color: white;
# }
# .sidebar-logo {
#     font-family: 'Poppins';
#     background: rgba(255,255,255,0.10);
#     border-radius: 18px;
#     padding: 20px;
#     text-align: center;
#     margin-bottom: 25px;
# }
# 
# /* PAGE TITLE */
# .page-title {
#     font-family: 'Poppins';
#     font-size: 40px;
#     font-weight: 800;
#     color: #0F172A;
# }
# 
# .page-subtitle {
#     font-family: 'Poppins';
#     color: #64748B;
#     margin-bottom: 30px;
# }
# /* ==========================
# TAB STYLING
# ========================== */
# 
# .stTabs [data-baseweb="tab-list"] {
#     font-family: 'Poppins';
#     border-radius: 18px;
#     font-size: 15px;
#     gap: 12px;
#     background: transparent;
#     margin-bottom: 25px;
# }
# 
# .stTabs [data-baseweb="tab"] {
#     background: #E2E8F0;
#     color: #475569;
#     border-radius: 18px;
#     padding: 14px 28px;
#     font-family: 'Poppins', poppins;
#     font-weight: 700;
#     font-size: 15px;
#     border: none;
#     transition: all 0.3s ease;
# }
# 
# /* Hover */
# .stTabs [data-baseweb="tab"]:hover {
#     background: #CBD5E1;
#     color: #0F172A;
# }
# 
# /* Active tab */
# .stTabs [aria-selected="true"] {
#     font-family: 'Poppins';
#     background: linear-gradient(
#         135deg,
#         #081F5C 0%,
#         #123C9C 100%
#     ) !important;
#     color: white !important;
#     box-shadow: 0px 8px 20px rgba(8,31,92,0.25);
# }
# 
# /* Hilangkan garis bawah bawaan */
# .stTabs [data-baseweb="tab-border"] {
#     display: none;
# }
# /* KPI */
# .kpi-box {
#     font-family: 'Poppins';
#     background: linear-gradient(
#         135deg,
#         #081F5C 0%,
#         #2563EB 100%
#     );
#     padding: 20px;
#     border-radius: 18px;
#     text-align: justified;
#     color: white;
# }
# 
# /* CHART CARD */
# .chart-card {
#     font-family: 'Poppins';
#     background: linear-gradient(
#         135deg,
#         #081F5C 0%,
#         #123C9C 100%
#     );
#     padding: 20px;
#     border-radius: 22px;
#     margin-bottom: 20px;
#     box-shadow: 0px 10px 30px rgba(8,31,92,0.25);
# }
# 
# /* INSIGHT CARD */
# .insight-card {
#     font-family: 'Poppins';
#     background: linear-gradient(
#         135deg,
#         #DBEAFE 0%,
#         #EFF6FF 100%
#     );
#     border-left: 5px solid #2563EB;
#     padding: 20px;
#     border-radius: 16px;
# }
# 
# </style>
# """, unsafe_allow_html=True)
# 
# # ==========================
# # SIDEBAR
# # ==========================
# st.sidebar.markdown("""
# <div class="sidebar-logo">
#     <h2>✈ AirInsight</h2>
#     <p>Passenger Analytics System</p>
# </div>
# """, unsafe_allow_html=True)
# 
# st.sidebar.markdown("---")
# 
# st.sidebar.subheader("Navigation")
# 
# st.sidebar.info(
#     "Explore analytical insights, compare machine learning models, and simulate passenger satisfaction predictions."
# )
# 
# 
# # ==========================
# # HEADER
# # ==========================
# st.markdown("""
# <div class="page-title">📊 Dashboard Analysis</div>
# <div class="page-subtitle">
# Explore passenger behavior, customer segmentation, and service quality insights.
# </div>
# """, unsafe_allow_html=True)
# 
# # ==========================
# # DARK BLUE CHART LAYOUT
# # ==========================
# chart_layout = dict(
#     paper_bgcolor="#081F5C",
#     plot_bgcolor="#081F5C",
#     font=dict(
#         family="Poppins, poppins",
#         color="white",
#         size=14
#     ),
#     title_font=dict(
#         family="Poppins, poppins",
#         size=20,
#         color="white",
#     ),
#     xaxis=dict(
#         gridcolor="rgba(255,255,255,0.08)",
#         tickfont=dict(color="white")
#     ),
#     yaxis=dict(
#         gridcolor="rgba(255,255,255,0.08)",
#         tickfont=dict(color="white")
#     ),
#     legend=dict(
#         font=dict(color="white")
#     )
# )
# 
# # ==========================
# # TABS
# # ==========================
# tab1, tab2, tab3 = st.tabs([
#     "Overview",
#     "Customer Demographics",
#     "Service Quality Analysis"
# ])
# 
# # ==========================
# # TAB 1
# # ==========================
# with tab1:
# 
#     col1, col2, col3, col4 = st.columns(4)
# 
#     metrics = [
#         ("Total Passenger", len(df)),
#         ("Features", df.shape[1]),
#         ("Avg Age", round(df["Age"].mean(),1)),
#         ("Avg Distance", round(df["Flight Distance"].mean(),1))
#     ]
# 
#     for col, (label, val) in zip([col1,col2,col3,col4], metrics):
#         with col:
#             st.markdown(f"""
#             <div class="kpi-box">
#                 <h4>{label}</h4>
#                 <h2>{val}</h2>
#             </div>
#             """, unsafe_allow_html=True)
# 
#     st.divider()
# 
#     st.markdown('<div class="chart-card">', unsafe_allow_html=True)
# 
#     fig1 = px.pie(
#         df,
#         names="satisfaction",
#         hole=0.65,
#         color_discrete_sequence=chart_colors,
#         title="Passenger Satisfaction Distribution"
#     )
#     fig1.update_traces(
#     textfont_color="white"
#     )
#     fig1.update_layout(**chart_layout, title_x=0.05, title_y=0.95, showlegend=True)
# 
#     st.plotly_chart(fig1, use_container_width=True)
#     st.markdown('</div>', unsafe_allow_html=True)
# 
# # ==========================
# # TAB 2
# # ==========================
# with tab2:
# 
#     col1, col2 = st.columns(2)
# 
#     with col1:
#         st.markdown('<div class="chart-card">', unsafe_allow_html=True)
# 
#         fig2 = px.histogram(
#             df,
#             x="Age",
#             color_discrete_sequence=["#60A5FA"],
#             title="Passenger Age Distribution"
#         )
#         fig2.update_layout(**chart_layout, title_x=0.05, title_y=0.95, showlegend=True)
# 
#         st.plotly_chart(fig2, use_container_width=True)
#         st.markdown('</div>', unsafe_allow_html=True)
# 
#     with col2:
#         st.markdown('<div class="chart-card">', unsafe_allow_html=True)
# 
#         fig3 = px.pie(
#             df,
#             names="Gender",
#             hole=0.65,
#             color_discrete_sequence=chart_colors,
#             title="Passenger Gender Composition"
#         )
#         fig3.update_layout(**chart_layout, title_x=0.05, title_y=0.95, showlegend=True)
# 
#         st.plotly_chart(fig3, use_container_width=True)
#         st.markdown('</div>', unsafe_allow_html=True)
# 
#     col3, col4 = st.columns(2)
# 
#     with col3:
#         st.markdown('<div class="chart-card">', unsafe_allow_html=True)
# 
#         fig4 = px.pie(
#             df,
#             names="Class",
#             hole=0.65,
#             color_discrete_sequence=chart_colors,
#             title="Flight Class Distribution"
#         )
#         fig4.update_layout(**chart_layout, title_x=0.05, title_y=0.95, showlegend=True)
# 
#         st.plotly_chart(fig4, use_container_width=True)
#         st.markdown('</div>', unsafe_allow_html=True)
# 
#     with col4:
#         st.markdown('<div class="chart-card">', unsafe_allow_html=True)
# 
#         fig5 = px.pie(
#             df,
#             names="Customer Type",
#             hole=0.65,
#             color_discrete_sequence=chart_colors,
#             title= "Customer Type Distribution"
#         )
#         fig5.update_layout(**chart_layout, title_x=0.05, title_y=0.95, showlegend=True)
# 
#         st.plotly_chart(fig5, use_container_width=True)
#         st.markdown('</div>', unsafe_allow_html=True)
# 
# # ==========================
# # TAB 3
# # ==========================
# with tab3:
# 
#     service_cols = [
#         "Inflight wifi service",
#         "Ease of Online booking",
#         "Food and drink",
#         "Seat comfort",
#         "Inflight entertainment",
#         "On-board service",
#         "Leg room service",
#         "Cleanliness"
#     ]
# 
#     avg_service = df[service_cols].mean().reset_index()
#     avg_service.columns = ["Service", "Rating"]
# 
#     st.markdown('<div class="chart-card">', unsafe_allow_html=True)
# 
#     fig6 = px.bar(
#         avg_service,
#         x="Rating",
#         y="Service",
#         orientation="h",
#         color="Rating",
#         color_continuous_scale=[
#             "#DBEAFE",
#             "#93C5FD",
#             "#60A5FA"],
#         title="Average Service Ratings"
#     )
#     fig6.update_layout(**chart_layout, title_x=0.05, title_y=0.95, showlegend=True)
# 
#     st.plotly_chart(fig6, use_container_width=True)
#     st.markdown('</div>', unsafe_allow_html=True)
# 
#     st.markdown('<div class="chart-card">', unsafe_allow_html=True)
# 
#     fig7 = px.box(
#         df,
#         y=service_cols,
#         color_discrete_sequence=["#93C5FD"],
#         title= "Service Rating Spread"
#     )
#     fig7.update_layout(**chart_layout, title_x=0.05, title_y=0.95, showlegend=True)
# 
#     st.plotly_chart(fig7, use_container_width=True)
#     st.markdown('</div>', unsafe_allow_html=True)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile pages/2_Model_Evaluation.py
# import streamlit as st
# import joblib
# import pandas as pd
# import plotly.express as px
# 
# # ==========================
# # PAGE CONFIG
# # ==========================
# st.set_page_config(
#     page_title="Model Evaluation",
#     page_icon="📉",
#     layout="wide"
# )
# 
# # ==========================
# # LOAD DATA
# # ==========================
# metrics = joblib.load("metrics.pkl")
# model = joblib.load("model_xgboost.pkl")
# 
# # ==========================
# # GLOBAL CSS
# # ==========================
# st.markdown("""
# <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet">
# 
# <style>
# 
# html, body, [class*="css"] {
#     font-family: 'Poppins', poppins;
# }
# 
# /* SIDEBAR */
# [data-testid="stSidebar"] {
#     font-family: 'Poppins', poppins;
#     background:
#     linear-gradient(
#         180deg,
#         #081F5C 0%,
#         #0F52BA 45%,
#         #2563EB 100%
#     );
#     padding-top: 20px;
# }
# 
# [data-testid="stSidebar"] * {
#     color: white;
# }
# .sidebar-logo {
#     font-family: 'Poppins', poppins;
#     background: rgba(255,255,255,0.10);
#     border-radius: 18px;
#     padding: 20px;
#     text-align: center;
#     margin-bottom: 25px;
# }
# 
# /* PAGE TITLE */
# .page-title {
#     font-family: 'Poppins', poppins;
#     font-size: 40px;
#     font-weight: 800;
#     color: #0F172A;
# }
# 
# .page-subtitle {
#     font-family: 'Poppins', poppins;
#     color: #64748B;
#     margin-bottom: 30px;
# }
# 
# /* ==========================
# TAB STYLING
# ========================== */
# 
# .stTabs [data-baseweb="tab-list"] {
#     font-family: 'Poppins', poppins;
#     border-radius: 18px;
#     font-size: 15px;
#     gap: 12px;
#     background: transparent;
#     margin-bottom: 25px;
# }
# 
# .stTabs [data-baseweb="tab"] {
#     background: #E2E8F0;
#     color: #475569;
#     border-radius: 18px;
#     padding: 14px 28px;
#     font-family: 'Poppins', poppins;
#     font-weight: 700;
#     font-size: 15px;
#     border: none;
#     transition: all 0.3s ease;
# }
# 
# /* Hover */
# .stTabs [data-baseweb="tab"]:hover {
#     font-family: 'Poppins', poppins;
#     background: #CBD5E1;
#     color: #0F172A;
# }
# 
# /* Active tab */
# .stTabs [aria-selected="true"] {
#     font-family: 'Poppins', poppins;
#     background: linear-gradient(
#         135deg,
#         #081F5C 0%,
#         #123C9C 100%
#     ) !important;
#     color: white !important;
#     box-shadow: 0px 8px 20px rgba(8,31,92,0.25);
# }
# 
# /* Hilangkan garis bawah bawaan */
# .stTabs [data-baseweb="tab-border"] {
#     font-family: 'Poppins', poppins;
#     display: none;
# }
# 
# /* KPI CARD */
# .kpi-box {
#     font-family: 'Poppins', poppins;
#     background: linear-gradient(
#         135deg,
#         #081F5C 0%,
#         #2563EB 100%
#     );
#     padding: 20px;
#     border-radius: 18px;
#     text-align: justified;
#     color: white;
#     box-shadow: 0px 8px 25px rgba(37,99,235,0.18);
# }
# 
# /* TABLE CARD */
# table {
#     font-family: 'Poppins', poppins;
#     text-align: center;
#     width: 100%;
#     border-collapse: collapse;
#     background: white;
#     border-radius: 16px;
#     overflow: hidden;
#     box-shadow: 0px 8px 20px rgba(0,0,0,0.08);
#     text-size: 8px;
# }
# 
# thead th {
#     font-family: 'Poppins', poppins;
#     background: linear-gradient(
#         135deg,
#         #081F5C 0%,
#         #123C9C 100%
#     );
#     color: white !important;
#     padding: 14px;
#     text-align: center;
#     test-size: 8px;
# }
# 
# tbody td {
#     font-family: 'Poppins', poppins;
#     padding: 12px;
#     text-align: center;
#     test-size: 8px;
# }
# 
# tbody tr:nth-child(even) {
#     font-family: 'Poppins', poppins;
#     background: #EFF6FF;
#     text-align: center;
#     test-size: 8px;
# }
# 
# tbody tr:hover {
#     font-family: 'Poppins', poppins;
#     background: #DBEAFE;
#     text-align: center;
#     test-size: 8px;
# }
# 
# /* STRIPED ROW */
# .table-card tbody tr:nth-child(even) td {
#     font-family: 'Poppins', poppins;
#     background: #EFF6FF;
# }
# 
# /* HOVER */
# .table-card tbody tr:hover td {
#     font-family: 'Poppins', poppins;
#     background: #DBEAFE;
#     transition: 0.3s;
# }
# 
# /* CHART CARD */
# .chart-card {
#     font-family: 'Poppins', poppins;
#     background: linear-gradient(
#         135deg,
#         #081F5C 0%,
#         #123C9C 100%
#     );
#     padding: 20px;
#     border-radius: 22px;
#     margin-bottom: 20px;
#     box-shadow: 0px 10px 30px rgba(8,31,92,0.25);
# }
# 
# /* INSIGHT CARD */
# .insight-card {
#     font-family: 'Poppins', poppins;
#     background: linear-gradient(
#         135deg,
#         #DBEAFE 0%,
#         #EFF6FF 100%
#     );
#     border-left: 5px solid #2563EB;
#     padding: 20px;
#     border-radius: 16px;
# }
# 
# </style>
# """, unsafe_allow_html=True)
# 
# # ==========================
# # SIDEBAR
# # ==========================
# st.sidebar.markdown("""
# <div class="sidebar-logo">
#     <h2>✈ AirInsight</h2>
#     <p>Passenger Analytics System</p>
# </div>
# """, unsafe_allow_html=True)
# 
# st.sidebar.markdown("---")
# 
# st.sidebar.subheader("Navigation")
# 
# st.sidebar.info(
#     "Explore analytical insights, compare machine learning models, and simulate passenger satisfaction predictions."
# )
# 
# # ==========================
# # HEADER
# # ==========================
# st.markdown("""
# <div class="page-title">📉 Model Evaluation & Insights</div>
# <div class="page-subtitle">
# Compare machine learning performance and analyze the most influential factors in predicting passenger satisfaction.
# </div>
# """, unsafe_allow_html=True)
# 
# # ==========================
# # CHART LAYOUT
# # ==========================
# chart_layout = dict(
#     paper_bgcolor="#081F5C",
#     plot_bgcolor="#081F5C",
#     font=dict(
#         family="Poppins",
#         color="white",
#         size=10
#     ),
#     title_font=dict(
#         family="Poppins",
#         size=14,
#         color="white",
#     ),
#     xaxis_title_font=dict(
#         family="Poppins",
#         size=10,
#         color="white"
#     ),
#     yaxis_title_font=dict(
#         family="Poppins",
#         size=10,
#         color="white"
#     ),
#     xaxis=dict(
#         gridcolor="rgba(255,255,255,0.08)",
#         tickfont=dict(color="white", family="Poppins", size=10)
#     ),
#     yaxis=dict(
#         gridcolor="rgba(255,255,255,0.08)",
#         tickfont=dict(color="white", family="Poppins", size=10)
#     ),
#     legend=dict(
#         font=dict(color="white", family="Poppins", size=10)
#     )
# )
# # ==========================
# # TABS
# # ==========================
# tab1, tab2 = st.tabs([
#     "📊 Model Performance",
#     "🧠 Feature Importance"
# ])
# 
# # ==========================
# # TAB 1
# # ==========================
# with tab1:
# 
#     # ==========================
#     # MODEL COMPARISON TABLE
#     # ==========================
#     st.subheader("Model Comparison Table")
# 
#     styled_metrics = metrics.style.format({
#         "Accuracy": "{:.2%}",
#         "Precision": "{:.2%}",
#         "Recall": "{:.2%}",
#         "F1 Score": "{:.2%}"
#     })
# 
#     st.markdown(
#     styled_metrics.to_html(),
#     unsafe_allow_html=True
#     )
#     # ==========================
#     # PERFORMANCE CHARTS
#     # ==========================
#     col1, col2 = st.columns(2)
# 
#     with col1:
#         st.markdown('<div class="chart-card">', unsafe_allow_html=True)
# 
#         fig1 = px.bar(
#             metrics,
#             x="Model",
#             y="Accuracy",
#             color="Accuracy",
#             title="Model Accuracy Comparison",
#             color_continuous_scale=[
#                 "#DBEAFE",
#                 "#93C5FD",
#                 "#60A5FA"
#             ]
#         )
# 
#         fig1.update_layout(**chart_layout, title_x=0.5)
# 
#         st.plotly_chart(fig1, use_container_width=True)
#         st.markdown('</div>', unsafe_allow_html=True)
# 
#     with col2:
#         metrics["Error Rate"] = 1 - metrics["Accuracy"]
# 
#         st.markdown('<div class="chart-card">', unsafe_allow_html=True)
# 
#         fig2 = px.bar(
#             metrics,
#             x="Model",
#             y="Error Rate",
#             color="Error Rate",
#             title="Model Error Rate Comparison",
#             color_continuous_scale=[
#                 "#BFDBFE",
#                 "#93C5FD",
#                 "#60A5FA"
#             ]
#         )
# 
#         fig2.update_layout(**chart_layout, title_x=0.5)
# 
#         st.plotly_chart(fig2, use_container_width=True)
#         st.markdown('</div>', unsafe_allow_html=True)
#     # ==========================
#     # BEST MODEL
#     # ==========================
#     best_model = metrics.sort_values(
#         by="Accuracy",
#         ascending=False
#     ).iloc[0]
#     # BEST MODEL TEXT
#     st.markdown(f"""
#     <div class="insight-card">
#         <h4>🏆 Best Model Selected</h4>
#         <p>
#           Based on performance evaluation, the best model is
#           <b>{best_model['Model']}</b>
#           with an accuracy of
#           <b>{best_model['Accuracy']:.2%}</b>.
#         </p>
#       </div>
#       """, unsafe_allow_html=True)
#     st.markdown("### Best Model Performance")
# 
#     col1, col2, col3, col4 = st.columns(4)
# 
#     kpis = [
#         ("Accuracy", f"{best_model['Accuracy']:.2%}"),
#         ("Precision", f"{best_model['Precision']:.2%}"),
#         ("Recall", f"{best_model['Recall']:.2%}"),
#         ("F1 Score", f"{best_model['F1 Score']:.2%}")
#     ]
# 
#     for col, (label, val) in zip([col1, col2, col3, col4], kpis):
#         with col:
#             st.markdown(f"""
#             <div class="kpi-box">
#                 <h4>{label}</h4>
#                 <h2>{val}</h2>
#             </div>
#             """, unsafe_allow_html=True)
# 
#     st.divider()
# # ==========================
# # TAB 2
# # ==========================
# with tab2:
# 
#     # ==========================
#     # FEATURE IMPORTANCE
#     # ==========================
#     st.subheader("Feature Importance")
# 
#     importance = model.feature_importances_
# 
#     features = [
#       "Gender",
#       "Customer Type",
#       "Age",
#       "Type of Travel",
#       "Class",
#       "Flight Distance",
#       "Inflight wifi service",
#       "Departure/Arrival time convenient",
#       "Ease of Online booking",
#       "Gate location",
#       "Food and drink",
#       "Online boarding",
#       "Seat comfort",
#       "Inflight entertainment",
#       "On-board service",
#       "Leg room service",
#       "Baggage handling",
#       "Checkin service",
#       "Inflight service",
#       "Cleanliness",
#       "Departure Delay in Minutes",
#       "Arrival Delay in Minutes"
#     ]
# 
#     df_imp = pd.DataFrame({
#         "Feature": features,
#         "Importance": importance
#     }).sort_values(
#         by="Importance",
#         ascending=False
#     )
# 
#     st.markdown('<div class="chart-card">', unsafe_allow_html=True)
# 
#     fig3 = px.bar(
#         df_imp.head(10),
#         x="Importance",
#         y="Feature",
#         orientation="h",
#         color="Importance",
#         title="Top 10 Most Important Features",
#         color_continuous_scale=[
#             "#DBEAFE",
#             "#93C5FD",
#             "#60A5FA"
#         ]
#     )
# 
#     fig3.update_layout(**chart_layout, title_x=0.5)
# 
#     st.plotly_chart(fig3, use_container_width=True)
#     st.markdown('</div>', unsafe_allow_html=True)
# 
#     # ==========================
#     # FULL FEATURE TABLE
#     # ==========================
#     st.subheader("All Feature Importance")
# 
#     styled_imp = df_imp.style.background_gradient(
#         subset=["Importance"],
#         cmap="Blues"
#     )
# 
#     st.markdown(
#     styled_imp.to_html(),
#     unsafe_allow_html=True
#     )
# 
#     # ==========================
#     # INSIGHT
#     # ==========================
#     st.markdown("""
#     <div class="insight-card">
#     <h4>Insight</h4>
#     <p>
#     Feature importance analysis helps identify which variables contribute the most to passenger satisfaction predictions.
#     This can support strategic service improvements and customer experience optimization.
#     </p>
#     </div>
#     """, unsafe_allow_html=True)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile pages/3_Prediction.py
# import streamlit as st
# import pandas as pd
# import joblib
# 
# # ==========================
# # PAGE CONFIG
# # ==========================
# st.set_page_config(
#     page_title="Prediction",
#     page_icon="🔮",
#     layout="wide"
# )
# 
# # ==========================
# # LOAD MODEL
# # ==========================
# model = joblib.load("model_xgboost.pkl")
# 
# # ==========================
# # GLOBAL CSS
# # ==========================
# st.markdown("""
# <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
# 
# <style>
# 
# html, body, [class*="css"] {
#     font-family: 'Poppins', poppins;
# }
# 
# /* SIDEBAR */
# [data-testid="stSidebar"] {
#     font-family: 'Poppins', poppins;
#     background:
#     linear-gradient(
#         180deg,
#         #081F5C 0%,
#         #0F52BA 45%,
#         #2563EB 100%
#     );
#     padding-top: 20px;
# }
# 
# [data-testid="stSidebar"] * {
#     color: white;
# }
# .sidebar-logo {
#     font-family: 'Poppins', poppins;
#     background: rgba(255,255,255,0.10);
#     border-radius: 18px;
#     padding: 20px;
#     text-align: center;
#     margin-bottom: 25px;
# }
# 
# /* PAGE TITLE */
# .page-title {
#     font-family: 'Poppins', poppins;
#     font-size: 40px;
#     font-weight: 800;
#     color: #0F172A;
# }
# 
# .page-subtitle {
#     font-family: 'Poppins', poppins;
#     color: #64748B;
#     margin-bottom: 30px;
# }
# 
# /* INPUT CARD */
# .input-card {
#     font-family: 'Poppins', poppins;
#     background: linear-gradient(
#         135deg,
#         #FFFFFF 0%,
#         #F8FAFC 100%
#     );
#     padding: 25px;
#     border-radius: 20px;
#     box-shadow: 0px 8px 25px rgba(0,0,0,0.05);
#     margin-bottom: 20px;
# }
# 
# /* SECTION TITLE */
# .section-title {
#     font-family: 'Poppins', poppins;
#     font-size: 22px;
#     font-weight: 800;
#     color: #1E3A8A;
#     margin-bottom: 15px;
# }
# 
# /* RESULT CARD */
# .result-card {
#     font-family: 'Poppins', poppins;
#     background: linear-gradient(
#         135deg,
#         #081F5C 0%,
#         #2563EB 100%
#     );
#     padding: 25px;
#     border-radius: 22px;
#     color: white;
#     text-align: center;
#     box-shadow: 0px 10px 30px rgba(37,99,235,0.20);
# }
# 
# /* BUTTON */
# .stButton > button {
#     font-family: 'Poppins', poppins;
#     width: 100%;
#     background: linear-gradient(
#         90deg,
#         #1D4ED8 0%,
#         #60A5FA 100%
#     );
#     color: white;
#     border: none;
#     border-radius: 14px;
#     padding: 12px;
#     font-weight: 700;
#     font-size: 15px;
# }
# /* FORM CONTAINER */
# .form-card {
#     background: linear-gradient(
#         135deg,
#         #FFFFFF 0%,
#         #F8FAFC 100%
#     );
#     padding: 28px;
#     border-radius: 24px;
#     box-shadow: 0px 12px 35px rgba(15,23,42,0.08);
#     margin-bottom: 25px;
#     border: 1px solid #E2E8F0;
# }
# 
# /* INPUT LABEL */
# label {
#     font-weight: 600 !important;
#     color: #1E293B !important;
# }
# 
# /* SELECTBOX */
# div[data-baseweb="select"] > div {
#     border-radius: 14px !important;
#     border: 1px solid #CBD5E1 !important;
#     background: white !important;
# }
# 
# /* NUMBER INPUT */
# div[data-baseweb="input"] > div {
#     border-radius: 14px !important;
#     border: 1px solid #CBD5E1 !important;
#     background: white !important;
# }
# 
# /* SLIDER */
# .stSlider > div[data-baseweb="slider"] {
#     padding-top: 10px;
# }
# 
# /* SLIDER TRACK */
# .stSlider [role="slider"] {
#     background: #2563EB !important;
#     border: 3px solid white !important;
# }
# 
# /* INFO CARD */
# .info-card {
#     background: linear-gradient(
#         135deg,
#         #DBEAFE 0%,
#         #EFF6FF 100%
#     );
#     border-left: 5px solid #2563EB;
#     padding: 18px;
#     border-radius: 16px;
#     margin-bottom: 20px;
# }
# 
# /* RESULT ANIMATION */
# .result-card {
#     animation: fadeIn 0.5s ease-in-out;
# }
# 
# @keyframes fadeIn {
#     from {opacity: 0; transform: translateY(20px);}
#     to {opacity: 1; transform: translateY(0);}
# }
# /* ==========================
# DROPDOWN / SELECTBOX
# ========================== */
# div[data-baseweb="select"] > div {
#     background: linear-gradient(
#         135deg,
#         #EFF6FF 0%,
#         #DBEAFE 100%
#     ) !important;
#     border: 2px solid #93C5FD !important;
#     border-radius: 14px !important;
#     min-height: 50px;
#     transition: 0.3s ease;
# }
# 
# div[data-baseweb="select"] > div:hover {
#     border: 2px solid #2563EB !important;
#     box-shadow: 0px 0px 12px rgba(37,99,235,0.25);
# }
# 
# /* Selected text */
# div[data-baseweb="select"] span {
#     color: #081F5C !important;
#     font-weight: 600;
# }
# 
# /* ==========================
# NUMBER INPUT
# ========================== */
# div[data-baseweb="input"] {
#     background: linear-gradient(
#         135deg,
#         #EFF6FF 0%,
#         #DBEAFE 100%
#     ) !important;
#     border-radius: 14px !important;
#     border: 2px solid #93C5FD !important;
# }
# 
# div[data-baseweb="input"]:hover {
#     border: 2px solid #2563EB !important;
# }
# 
# /* ==========================
# SLIDER CONTAINER
# ========================== */
# .stSlider {
#     background: linear-gradient(
#         135deg,
#         #EFF6FF 0%,
#         #F8FAFC 100%
#     );
#     padding: 15px;
#     border-radius: 16px;
#     margin-bottom: 12px;
#     border: 1px solid #DBEAFE;
# }
# 
# /* Slider track */
# .stSlider [data-baseweb="slider"] > div > div {
#     background: #93C5FD !important;
# }
# 
# /* Active track */
# .stSlider [role="slider"] {
#     background: #2563EB !important;
#     border: 3px solid white !important;
#     width: 20px !important;
#     height: 20px !important;
#     box-shadow: 0px 0px 12px rgba(37,99,235,0.4);
# }
# 
# /* ==========================
# LABELS
# ========================== */
# label {
#     font-size: 15px !important;
#     font-weight: 700 !important;
#     color: #1E3A8A !important;
# }
# </style>
# """, unsafe_allow_html=True)
# 
# # ==========================
# # SIDEBAR
# # ==========================
# st.sidebar.markdown("""
# <div class="sidebar-logo">
#     <h2>✈ AirInsight</h2>
#     <p>Passenger Analytics System</p>
# </div>
# """, unsafe_allow_html=True)
# 
# st.sidebar.markdown("---")
# 
# st.sidebar.subheader("Navigation")
# 
# st.sidebar.info(
#     "Explore analytical insights, compare machine learning models, and simulate passenger satisfaction predictions."
# )
# 
# 
# # ==========================
# # HEADER
# # ==========================
# st.markdown("""
# <div class="page-title">🔮 Passenger Satisfaction Prediction</div>
# <div class="page-subtitle">
# Simulate passenger scenarios and predict airline satisfaction in real-time.
# </div>
# """, unsafe_allow_html=True)
# 
# # ==========================
# # INPUT FORM
# # ==========================
# st.markdown('<div class="section-title">Passenger Information</div>', unsafe_allow_html=True)
# 
# st.markdown("""
# <div class="info-card">
# Fill in passenger profile and service ratings to simulate airline satisfaction prediction.
# </div>
# """, unsafe_allow_html=True)
# 
# st.markdown('<div class="form-card">', unsafe_allow_html=True)
# 
# col1, col2 = st.columns(2)
# 
# with col1:
#     gender = st.selectbox("Gender", ["Male", "Female"])
#     customer_type = st.selectbox("Customer Type", ["Loyal Customer", "Disloyal Customer"])
#     age = st.number_input("Age", 1, 100)
#     travel_type = st.selectbox("Type of Travel", ["Business Travel", "Personal Travel"])
#     flight_class = st.selectbox("Class", ["Business", "Eco", "Eco Plus"])
#     flight_distance = st.number_input("Flight Distance", 0)
# 
# with col2:
#     wifi = st.slider("Inflight wifi service", 0, 5)
#     seat_comfort = st.slider("Seat comfort", 0, 5)
#     cleanliness = st.slider("Cleanliness", 0, 5)
#     online_booking = st.slider("Ease of Online booking", 0, 5)
#     entertainment = st.slider("Inflight entertainment", 0, 5)
#     onboard_service = st.slider("On-board service", 0, 5)
# 
# st.markdown('</div>', unsafe_allow_html=True)
# # ==========================
# # ENCODING MAPPING
# # ==========================
# gender_map = {
#     "Male": 1,
#     "Female": 0
# }
# 
# customer_type_map = {
#     "Loyal Customer": 1,
#     "Disloyal Customer": 0
# }
# 
# travel_type_map = {
#     "Business Travel": 1,
#     "Personal Travel": 0
# }
# 
# class_map = {
#     "Business": 0,
#     "Eco": 1,
#     "Eco Plus": 2
# }
# 
# # fixed filler values for remaining features
# input_data = pd.DataFrame({
#     "Gender": [gender_map[gender]],
#     "Customer Type": [customer_type_map[customer_type]],
#     "Age": [age],
#     "Type of Travel": [travel_type_map[travel_type]],
#     "Class": [class_map[flight_class]],
#     "Flight Distance": [flight_distance],
#     "Inflight wifi service": [wifi],
#     "Departure/Arrival time convenient": [3],
#     "Ease of Online booking": [online_booking],
#     "Gate location": [3],
#     "Food and drink": [3],
#     "Online boarding": [3],
#     "Seat comfort": [seat_comfort],
#     "Inflight entertainment": [entertainment],
#     "On-board service": [onboard_service],
#     "Leg room service": [3],
#     "Baggage handling": [3],
#     "Checkin service": [3],
#     "Inflight service": [3],
#     "Cleanliness": [cleanliness],
#     "Departure Delay in Minutes": [0],
#     "Arrival Delay in Minutes": [0]
# })
# 
# st.markdown("""
# <div class="info-card">
# <h4>Passenger Summary</h4>
# <ul>
# <li><b>Gender:</b> {}</li>
# <li><b>Customer Type:</b> {}</li>
# <li><b>Travel Type:</b> {}</li>
# <li><b>Class:</b> {}</li>
# <li><b>Age:</b> {}</li>
# <li><b>Flight Distance:</b> {} km</li>
# </ul>
# </div>
# """.format(
#     gender,
#     customer_type,
#     travel_type,
#     flight_class,
#     age,
#     flight_distance
# ), unsafe_allow_html=True)
# 
# # ==========================
# # PREDICT BUTTON
# # ==========================
# if st.button("Predict Satisfaction"):
# 
#     prediction = model.predict(input_data)
#     proba = model.predict_proba(input_data)
# 
#     confidence = max(proba[0])
# 
#     st.markdown('<div class="section-title">Prediction Result</div>', unsafe_allow_html=True)
# 
#     if prediction[0] == 1:
#         st.markdown(f"""
#         <div class="result-card">
#             <h2>✅ Passenger Satisfied</h2>
#             <p>Confidence Score: {confidence*100:.2f}%</p>
#         </div>
#         """, unsafe_allow_html=True)
#     else:
#         st.markdown(f"""
#         <div class="result-card">
#             <h2>⚠ Passenger Dissatisfied</h2>
#             <p>Confidence Score: {confidence*100:.2f}%</p>
#         </div>
#         """, unsafe_allow_html=True)
# 
#     st.progress(float(confidence))




from pyngrok import ngrok

ngrok.kill()

ngrok.set_auth_token("3EvgCT3YmB9xDXNjhiv18zktHbY_5N4pg9dG2X69esV99rBGC")

url = ngrok.connect(8501)
print(url)

print(X_train.columns.tolist())

from google.colab import files
files.download('model_xgboost.pkl')

import joblib
metrics = {
    "Logistic Regression": {"accuracy": 0.8699, "precision": 0.8697, "recall": 0.8699, "f1": 0.8697},
    "Random Forest":       {"accuracy": 0.9563, "precision": 0.9563, "recall": 0.9563, "f1": 0.9563},
    "XGBoost":             {"accuracy": 0.9611, "precision": 0.9612, "recall": 0.9611, "f1": 0.9611},
}
joblib.dump(metrics, "metrics.pkl")
files.download("metrics.pkl")

from google.colab import files
files.download('model_xgboost.pkl')
files.download('test.csv')
